### ISSUE TITLE
Can't repack the bin after export json from editor

### ISSUE THREAD

**Issue by nokhzz** [chm-dev/GTS-watchface-bundle#3]
I don't know why, but I can't pack any folder after export the new json from editor.

> NameError: name 'FileNotFoundException' is not defined
2020-01-08 23:44:39,263 - root - ERROR - [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Users\\Eduardo\\Desktop\\GTS\\GTS-watchface-bundle\\faces\\gts_google_black-155712-91ce0f0122_unp\\gts_google_black-155712-91ce0f0122_unp_packed.bin'
Traceback (most recent call last):
  File "program.py", line 61, in writeWatchFace
  File "watchFaceParser\utils\resourcesLoader.py", line 94, in process
  File "watchFaceParser\utils\resourcesLoader.py", line 94, in process
  File "watchFaceParser\utils\resourcesLoader.py", line 94, in process
  [Previous line repeated 1 more time]
  File "watchFaceParser\utils\resourcesLoader.py", line 73, in process
  File "watchFaceParser\utils\resourcesLoader.py", line 108, in loadImage
  File "resources\imageLoader.py", line 21, in loadResourceForNumber
NameError: name 'FileNotFoundException' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "program.py", line 112, in packWatchFace
  File "program.py", line 76, in writeWatchFace
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Users\\Eduardo\\Desktop\\GTS\\GTS-watchface-bundle\\faces\\gts_google_black-155712-91ce0f0122_unp\\gts_google_black-155712-91ce0f0122_unp_packed.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 35, in <module>
  File "program.py", line 114, in packWatchFace
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Users\\Eduardo\\Desktop\\GTS\\GTS-watchface-bundle\\faces\\gts_google_black-155712-91ce0f0122_unp\\gts_google_black-155712-91ce0f0122_unp_packed.bin'

**Comment by JSsantana** [comment]
Eu percebi que ao habilitar a bateria via numero, ele dá esse erro. Estranho.
